### ISSUE TITLE
Function expressions are not supported in decorators in 'NgModule'

### ISSUE THREAD

**Issue by matheushf** [matheushf/ng2-date-countdown#6]
Trying to make AOT compatible, creating an Module to import the CountdownComponent, and bundle them with ngc after inline the templates. 

WIth AOT gives the following error:

```
Error during template compile of 'CountDownModule'
  Function expressions are not supported in decorators in 'NgModule'
    'NgModule' contains the error at ../@angular/core/core.ts(194,31)
      Consider changing the function expression into an exported function.
```

[Branch AOT](https://github.com/matheushf/ng2-date-countdown/tree/AOT)

#4

**Comment by timelf123** [comment]
Haven't looked at your branch yet but be sure you aren't decorating with a function expression. I just fixed this in my app:
![s0nnaaq 1](https://user-images.githubusercontent.com/2816999/36061095-e24ffbc4-0e1a-11e8-8a2c-5a00224eadf7.png)

**Comment by kshkrao3** [comment]
@matheushf I was able to successfully build this version with `npm run buildNEW`. When you get this error actually? Did you add `peerDependencies` in `package.json`?

Let me know.

**Comment by matheushf** [comment]
@timelf123  unfortunately I'm not using function expressions in my decorator, so it can't be the problem. But thanks!

All the builds are working  @kshkrao3, the problem is when importing it in the actual app to use it, then we get the error. I've seen more people with this error in some issues around, but no success yet

**Comment by kshkrao3** [comment]
@matheushf I've dropped my comments on [#5](https://github.com/matheushf/ng2-date-countdown/pull/5). Could you please look into that once?

**Comment by mcblum** [comment]
@matheushf thanks for your work on this. We're still seeing an error when trying to build with AOT. Is this the same error that's being discussed here?

`ERROR in : Unexpected value 'CountDown in /www/app/node_modules/ng2-date-countdown/dist/countdown.d.ts' declared by the module 'TicketingModule in /www/app/libs/ticketing/src/ticketing.module.ts'. Please add a @Pipe/@Directive/@Component annotation.`

**Comment by matheushf** [comment]
This is one of the errors. I should have put in the issue, this one happens with a different kind of build, I forgot now but I'll check it again.

Thanks!

**Comment by mcblum** [comment]
No worries dude - for whatever reason when I just copied / pasted your component and fixed a couple things the linter was whining about it worked great. You accepting PRs?

**Comment by matheushf** [comment]
Oh, cool! Yes please. Did you test it building and then npm link? Because when you just use the component .ts in  your project it works even with AOT

**Comment by Abadii** [comment]
Is the AOT fix in progress?

**Comment by PTC-JoshuaMatthews** [comment]
Also interested if fix is in progress, I've changed to exported function and issue is still not resolved.
